
server {
    listen 80;

    # serve the React app
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # forward /api requests to backend container
    location /api {
        proxy_pass http://backend:3000;
    }

    # forward /auth requests to backend container
    location /auth {
        proxy_pass http://backend:3000;
    }

    # forward /health requests to backend container
    location /health {
        proxy_pass http://backend:3000;
    }
}